# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9da38c9bf2da0e8838c0ae7109f4fbf3cad6512044de7ff2ee1f60533b7abc998b20349facb97a9ceec0399531cd720664c2f6a99b0c358d83b9ef627eafad95

test:
  secret_key_base: 8d546cc7a0950955c6be476ab490503d656d17772c715160a42e18e3e15c8b29b1e3b1553a03cdf0c2f9a7b1014fea4bd29febcee465f56a3c5508bf7bf0f4bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
